# Generated by Django 2.0.3 on 2018-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_projects'),
        ('projects', '0002_auto_20180424_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
