FROM python:3.5
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

ARG DJANGO_SECRET_KEY
ARG FRONT_END_URL
ARG DATABASE_URL
ARG DEBUG 

ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
ENV FRONT_END_URL=$FRONT_END_URL
ENV DATABASE_URL=$DATABASE_URL
ENV DEBUG=$DEBUG

ADD . /code/
RUN pip install -r requirements.txt && \
    chmod +x boot.sh

CMD bin/sh ./boot.sh
