version: '3'

services:

  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5000:5432

  web:
    build: .
    command: /bin/sh ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017

  metabase:
    build: metabase-docker/
    ports:
      - "3000:3000"
    environment:
        MB_DB_TYPE: "${MB_DB_TYPE}"
        MB_DB_DBNAME: "${MB_DB_DBNAME}"
        MB_DB_PORT: "${MB_DB_PORT}"
        MB_DB_USER: "${MB_DB_USER}"
        MB_DB_PASS: "${MB_DB_PASS}"
        MB_DB_HOST: "${MB_DB_HOST}"
        MB_FIRST_NAME: "${MB_FIRST_NAME}" 
        MB_LAST_NAME: "${MB_LAST_NAME}" 
        MB_EMAIL: "${MB_EMAIL}" 
        MB_PASSWORD: "${MB_PASSWORD}" 
    depends_on:
      - db
      - mongo
